### ISSUE TITLE
Official Todo List for Both Apps

### ISSUE THREAD

**Issue by roboteer5291** [TOWR5291/TOWR5291-2017-2018-Scouting-App#2]
TODO:

- [ ] Add buttons on comments screen for specific robot failures, broke down, comms issue, etc.
- [ ] Add "Attempted Relic" button that unlocks the relic zone/standing selectors
- [ ] Create Viewer App
- [ ] Organize resources (String, competition resources, etc.) into separate files and within the file they are in
- [ ] Make the app able to specify team lists with a csv file, making it release ready.
- [ ] Make it like TORC's, with fragments and such (not the whole complex system of MatchData and MatchDatabaseHelper classes)
